name: Test Connexion
on: [push] # Se déclenche à chaque fois que vous envoyez du code
jobs:
  coucou:
    runs-on: ubuntu-latest
    steps:
      - name: Message de test
        run: echo "Le terrain est prêt pour Supabase !"
