name: Deploy SQL to Supabase

on:
  push:
    branches:
      - main
    paths:
      - 'backend/supabase/migrations/**' # Se lance dès que vous changez le SQL

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link and Push to Supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Migrations
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --password ${{ secrets.SUPABASE_DB_PASSWORD }}
          supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
